/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 MotorcycleModelWithStand.glb 
*/

import React, { useRef,useEffect } from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelWithStand(props) {
  const { nodes, materials } = useGLTF('models/MotorcycleModelWithStand.glb')

  const motorRef = useRef()
  document.motorIns = motorRef
  useEffect(() => {
    motorRef.current.rotation.y = -0.7;
    // motorRef.current.rotation.x = 0.2;
    motorRef.current.scale.x = 2
    motorRef.current.scale.y = 2
    motorRef.current.scale.z = 2
  }, [])
  return (
    <group position={[0,-0.9,0]} ref={motorRef} {...props} dispose={null}>
      <group position={[0, 0.896, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={1.087}>
        <group position={[0, 0, -0.391]}>
          <mesh geometry={nodes.Object_10.geometry} material={materials.headlight} />
          {/* <mesh geometry={nodes.Object_11.geometry} material={materials.hondaF} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.hondaR} /> */}
          <mesh geometry={nodes.Object_13.geometry} material={materials.matedetails} />
          <mesh geometry={nodes.Object_14.geometry} material={materials.mirrors} />
          <mesh geometry={nodes.Object_15.geometry} material={materials.plasticdetails} />
          <mesh geometry={nodes.Object_16.geometry} material={materials.sidereflectors} />
          <mesh geometry={nodes.Object_17.geometry} material={materials.spdglass} />
          <mesh geometry={nodes.Object_18.geometry} material={materials.tire} />
          <mesh geometry={nodes.Object_2.geometry} material={materials.Honda_Shadow_RS_2010_by_Alex_Ka} />
          <mesh geometry={nodes.Object_3.geometry} material={materials.aluminiumdetails} />
          <mesh geometry={nodes.Object_4.geometry} material={materials.black_chrome} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.black_mate} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.black_plastic} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.brakelight} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.chrome} />
          <mesh geometry={nodes.Object_9.geometry} material={materials.chromedetails} />
        </group>
      </group>
      <mesh geometry={nodes.Cube.geometry}  position={[0.1, 0.397, 0.085]} rotation={[-Math.PI, 0, 0]} scale={1.302} >
        <meshStandardMaterial color={'white'} emissive={'#fff'} />
      </mesh>
      <mesh geometry={nodes.Sphere.geometry} position={[0.008, 0.409, 0.116]} rotation={[0, 0, Math.PI]} scale={[1.159, 1, 1]} >
      <meshStandardMaterial color={'grey'} emissive={'#fff'} />
      </mesh>
    </group>
  )
}

useGLTF.preload('models/MotorcycleModelWithStand.glb')
